-- SQL Export for Specialty HRT0702/01V
-- Generated at: 2026-07-14 22:04:00
SET FOREIGN_KEY_CHECKS = 0;

-- Table: specialite
INSERT IGNORE INTO `specialite` (`IDSpecialite`, `IDBranche`, `IDNiveau_Fp`, `IDqualification_dplm`, `Nom`, `NomFr`, `NbrSem`, `IDNiveau_Scol`, `NbrAnne`, `CodeSpec`, `IDNomenclature`, `dureeM`, `IDNomenclature_Mode`, `DureeH`, `activee`, `conditionsArabe`, `conditionsLatin`, `Obs`, `DureeHHebdo`, `DureeStageM`, `DureeStageHbdo`, `PeriodeStage`, `Datedernierprogramme`, `dureemiseajour`, `PE`, `PEAPP`, `PAAR`, `PEAPPAR`, `RAP`, `RCC`, `PLANEQUIP`, `FICHEPROFIL`, `FICHEPROFILAR`, `NomEn`, `PLANEQUIPAR`, `IDsousdomaine_rnfc`) VALUES (744, 13, 1, 4, '', 'Fabriquer les diff├®rents types de pains', 0, 0, 0, 'HRT0702/01V', 0, 0, 6, 0, 0, '', '', '', 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 0);

-- Table: section
INSERT IGNORE INTO `section` (`IDSection`, `IDOffre`, `DateDF`, `IDMode_formation`, `DateFF`, `Nom`, `NomFr`, `CodeSectionEtat`, `CodeSectionEtat1`, `CodeSectionEtat2`, `Nbrrecond`, `Nbrrecondf`, `Duree`, `DureeH`, `Groupe`, `NbrIncor`, `NbrIncorF`, `IDSectionN`, `visadfep`, `visadir`, `nbrdplm`, `nbrdplmf`, `Obs`, `nbrincoretr`, `nbrincoretrf`, `nbrincorend`, `nbrincorendf`, `visacentral`, `Validation`, `ValidationDfp`, `Fermee`, `Cloturee`, `SectionPourRoudoub`, `IDEncadrement`, `NumPromotion`, `NumPv`, `DatePv`, `NumPvFin`, `DatePvFin`, `nbrdplmetr`, `nbrdplmetrf`, `nbrdplmend`, `nbrdplmendf`, `CodeSpec`, `IDEts_Form`, `IDEts_FormM`, `IDSpecialite`, `NbrSem`, `NbrAnne`, `ExaminFin`, `visafinal`, `visafinaldfp`, `IDDFEP`, `erreurs`, `indices`, `IDSession`, `numSerieDiplomedeb`, `numSerieDiplomefin`, `IDMois`) VALUES (203266, 258802, '2026-03-24', 24, '2026-04-23', NULL, 'Fabriquer les différents types de pains', NULL, NULL, NULL, 0, 0, 0, 0, 1, 5, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, '2026-03-24', 0, NULL, 0, 0, 0, 0, 'HRT0702/01V', 483, 483, 744, 0, 0, 0, 0, 0, 0, NULL, NULL, 35, NULL, NULL, 0);

-- Table: offre
INSERT IGNORE INTO `offre` (`IDOffre`, `IDSession`, `IDSpecialite`, `IDMode_formation`, `DateD`, `DateF`, `DateVisiteAtelier`, `DateVisiteMedical`, `encadrement`, `Programme`, `Equipement`, `DateSelection`, `NbrInscr`, `NbrInscrf`, `nbrPrevision`, `IDEts_Form`, `IDEts_FormM`, `ValidDfp`, `ValideCentral`, `Valide`, `brigde`, `EtatSection`, `IDMihnati`, `Obs`, `nbrGroupe`, `NbrinscMihnati`, `NbrPreinscMihnati`, `NbrincoMihnati`, `IDOffreN`, `IDMois`, `Datesselction`, `Nbrinco`, `Nbrincof`, `ValidationDfp`, `Nom_specialite_carte`, `IDqualification_dplm`, `Obs_Dfep`, `Obs_Central`, `Nom_specialite_cartefr`) VALUES (214253, 33, 744, 24, '2025-02-23', '2025-01-12', NULL, NULL, 0, 0, 0, NULL, 0, 0, 5, 215, 215, 1, 1, 0, 1, 1, 0, '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, '', 0, '', '', '');
INSERT IGNORE INTO `offre` (`IDOffre`, `IDSession`, `IDSpecialite`, `IDMode_formation`, `DateD`, `DateF`, `DateVisiteAtelier`, `DateVisiteMedical`, `encadrement`, `Programme`, `Equipement`, `DateSelection`, `NbrInscr`, `NbrInscrf`, `nbrPrevision`, `IDEts_Form`, `IDEts_FormM`, `ValidDfp`, `ValideCentral`, `Valide`, `brigde`, `EtatSection`, `IDMihnati`, `Obs`, `nbrGroupe`, `NbrinscMihnati`, `NbrPreinscMihnati`, `NbrincoMihnati`, `IDOffreN`, `IDMois`, `Datesselction`, `Nbrinco`, `Nbrincof`, `ValidationDfp`, `Nom_specialite_carte`, `IDqualification_dplm`, `Obs_Dfep`, `Obs_Central`, `Nom_specialite_cartefr`) VALUES (258802, 35, 744, 24, '2026-02-15', '2026-04-23', NULL, NULL, 1, 1, 1, NULL, 5, 0, 25, 483, 483, 1, 1, 1, 1, 1, 0, NULL, 1, 0, 0, 0, 0, 0, NULL, 5, 0, 1, NULL, 0, NULL, NULL, NULL);

-- Table: candidat
INSERT IGNORE INTO `candidat` (`IDCandidat`, `IDOffre`, `Nom`, `NomFr`, `Prenom`, `PrenomFr`, `DateNais`, `LieuNaisFr`, `LieuNais`, `NumIns`, `Presume`, `IDDecision_Insc`, `IDNiveau_Scol`, `PrenomPereFr`, `PrenomPere`, `NomMereFr`, `IdMihnati`, `PrenomMereFr`, `NbrAnneExp`, `NomMere`, `Civ`, `PrenomMere`, `IDqualification_dplm`, `NumWassit`, `GroupeExa`, `Valide`, `IDEts_Scolaire`, `IDFiliere`, `dateInscr`, `IDNationalitee`, `IDCandidatN`, `endicape`, `Adres`, `AdresFr`, `Obs`, `Nationalite`, `Validation`, `ValidationDfp`, `Nss`, `IdMihnati1`, `DerogationAge`, `IDCommunn`, `IDWilayaa`, `IDCommunR`, `IDWilayaR`, `sansParant`, `Nin`, `NumActeNais`, `IDPreinscrit`, `Premier`, `Tel`, `niscolaire`, `annescolaire`, `datesortirscolaire`, `numcertificatscolaire`, `datecertificatscolaire`, `email`, `Tel2`, `email2`, `photo`, `ninscscolaire`, `boursier`, `create_time`, `update_time`, `data_sync_time`) VALUES (3274759, 258802, 'مسعودان', 'messaoudane', 'فاروق', 'farouk', '1994/07/06', 'bordj bou areridj', 'برج بوغريريج', '0007126VC3407', 0, 1, 10, NULL, 'الحسين', 'bahih', 0, 'taous', 0, 'بحيح', 1, 'الطاوس', 0, NULL, 0, 0, 26494, 7, '2026-03-25', 1, 0, 0, 'بلدية اليشير', 'comune el yachir', NULL, 1, 0, 0, NULL, 0, 0, 3401, 34, 3411, 34, 255, 109941164038440009, 03844, 0, 0, NULL, NULL, '2011/2010', '2011-06-30', '2026/53', '2026-04-22', NULL, NULL, NULL, NULL, NULL, 0, '2026-06-02 00:00:00', '2026-06-02', NULL);
INSERT IGNORE INTO `candidat` (`IDCandidat`, `IDOffre`, `Nom`, `NomFr`, `Prenom`, `PrenomFr`, `DateNais`, `LieuNaisFr`, `LieuNais`, `NumIns`, `Presume`, `IDDecision_Insc`, `IDNiveau_Scol`, `PrenomPereFr`, `PrenomPere`, `NomMereFr`, `IdMihnati`, `PrenomMereFr`, `NbrAnneExp`, `NomMere`, `Civ`, `PrenomMere`, `IDqualification_dplm`, `NumWassit`, `GroupeExa`, `Valide`, `IDEts_Scolaire`, `IDFiliere`, `dateInscr`, `IDNationalitee`, `IDCandidatN`, `endicape`, `Adres`, `AdresFr`, `Obs`, `Nationalite`, `Validation`, `ValidationDfp`, `Nss`, `IdMihnati1`, `DerogationAge`, `IDCommunn`, `IDWilayaa`, `IDCommunR`, `IDWilayaR`, `sansParant`, `Nin`, `NumActeNais`, `IDPreinscrit`, `Premier`, `Tel`, `niscolaire`, `annescolaire`, `datesortirscolaire`, `numcertificatscolaire`, `datecertificatscolaire`, `email`, `Tel2`, `email2`, `photo`, `ninscscolaire`, `boursier`, `create_time`, `update_time`, `data_sync_time`) VALUES (3274760, 258802, 'ناوي', 'naoui', 'سمير', 'samir', '1996/08/22', 'bordj bou areridj', 'برج بوعريريج', '0003126VC3407', 0, 1, 11, NULL, 'محمد', 'naoui', 0, 'mbarka', 0, 'ناوي', 1, 'مباركة', 0, NULL, 0, 0, 26590, 7, '2026-03-25', 1, 0, 0, 'ماجن عمران', 'majen oumran', NULL, 1, 0, 0, NULL, 0, 0, 3401, 34, 3411, 34, 255, 109961164040360000, 04036, 0, 0, NULL, NULL, '2014/2013', '2014-06-30', 71, '2026-04-23', NULL, NULL, NULL, NULL, NULL, 0, '2026-06-01 18:43:19', '2026-06-01', NULL);
INSERT IGNORE INTO `candidat` (`IDCandidat`, `IDOffre`, `Nom`, `NomFr`, `Prenom`, `PrenomFr`, `DateNais`, `LieuNaisFr`, `LieuNais`, `NumIns`, `Presume`, `IDDecision_Insc`, `IDNiveau_Scol`, `PrenomPereFr`, `PrenomPere`, `NomMereFr`, `IdMihnati`, `PrenomMereFr`, `NbrAnneExp`, `NomMere`, `Civ`, `PrenomMere`, `IDqualification_dplm`, `NumWassit`, `GroupeExa`, `Valide`, `IDEts_Scolaire`, `IDFiliere`, `dateInscr`, `IDNationalitee`, `IDCandidatN`, `endicape`, `Adres`, `AdresFr`, `Obs`, `Nationalite`, `Validation`, `ValidationDfp`, `Nss`, `IdMihnati1`, `DerogationAge`, `IDCommunn`, `IDWilayaa`, `IDCommunR`, `IDWilayaR`, `sansParant`, `Nin`, `NumActeNais`, `IDPreinscrit`, `Premier`, `Tel`, `niscolaire`, `annescolaire`, `datesortirscolaire`, `numcertificatscolaire`, `datecertificatscolaire`, `email`, `Tel2`, `email2`, `photo`, `ninscscolaire`, `boursier`, `create_time`, `update_time`, `data_sync_time`) VALUES (3274761, 258802, 'بن جدي', 'bendjedi', 'العمري', 'lamri', '1997/05/13', 'setif', 'سطيف', '0005126VC3407', 0, 1, 22, 'kalifa', 'خليفة', 'dechache', 0, 'malika', 0, 'دشاش', 1, 'مليكة', 0, NULL, 0, 0, 26452, 17, '2026-03-25', 1, 0, 0, 'بلدية المهير', 'comune elmhir', NULL, 1, 0, 0, NULL, 0, 0, 1901, 19, 3405, 34, 255, 109970675028720005, 02872, 0, 0, NULL, 1099719010287200, '2018/2017', '2018-06-30', 111, '2026-03-23', NULL, NULL, NULL, NULL, 8, 0, '2026-06-01 16:49:44', '2026-06-01', NULL);
INSERT IGNORE INTO `candidat` (`IDCandidat`, `IDOffre`, `Nom`, `NomFr`, `Prenom`, `PrenomFr`, `DateNais`, `LieuNaisFr`, `LieuNais`, `NumIns`, `Presume`, `IDDecision_Insc`, `IDNiveau_Scol`, `PrenomPereFr`, `PrenomPere`, `NomMereFr`, `IdMihnati`, `PrenomMereFr`, `NbrAnneExp`, `NomMere`, `Civ`, `PrenomMere`, `IDqualification_dplm`, `NumWassit`, `GroupeExa`, `Valide`, `IDEts_Scolaire`, `IDFiliere`, `dateInscr`, `IDNationalitee`, `IDCandidatN`, `endicape`, `Adres`, `AdresFr`, `Obs`, `Nationalite`, `Validation`, `ValidationDfp`, `Nss`, `IdMihnati1`, `DerogationAge`, `IDCommunn`, `IDWilayaa`, `IDCommunR`, `IDWilayaR`, `sansParant`, `Nin`, `NumActeNais`, `IDPreinscrit`, `Premier`, `Tel`, `niscolaire`, `annescolaire`, `datesortirscolaire`, `numcertificatscolaire`, `datecertificatscolaire`, `email`, `Tel2`, `email2`, `photo`, `ninscscolaire`, `boursier`, `create_time`, `update_time`, `data_sync_time`) VALUES (3274762, 258802, 'سنوسي', 'snousi', 'علاء الدين', 'ala addine', '2002/03/21', 'teniet enaser', 'ثنية النصر', '0002126VC3407', 0, 1, 22, 'amar', 'عمار', 'saidi', 0, 'saidi', 0, 'سسعديدي', 1, 'فتيحة', 0, NULL, 0, 0, 26318, 16, '1960-03-25', 1, 0, 0, 'بلدية مجانة', 'comune medjana', NULL, 1, 0, 0, NULL, 0, 0, 3414, 34, 3413, 34, 255, 100021189000300008, 00030, 0, 0, NULL, NULL, '2012/2011', '2022-06-30', 2014, '2026-04-20', NULL, NULL, NULL, NULL, NULL, 0, '2026-06-02 08:59:52', '2026-06-02', NULL);
INSERT IGNORE INTO `candidat` (`IDCandidat`, `IDOffre`, `Nom`, `NomFr`, `Prenom`, `PrenomFr`, `DateNais`, `LieuNaisFr`, `LieuNais`, `NumIns`, `Presume`, `IDDecision_Insc`, `IDNiveau_Scol`, `PrenomPereFr`, `PrenomPere`, `NomMereFr`, `IdMihnati`, `PrenomMereFr`, `NbrAnneExp`, `NomMere`, `Civ`, `PrenomMere`, `IDqualification_dplm`, `NumWassit`, `GroupeExa`, `Valide`, `IDEts_Scolaire`, `IDFiliere`, `dateInscr`, `IDNationalitee`, `IDCandidatN`, `endicape`, `Adres`, `AdresFr`, `Obs`, `Nationalite`, `Validation`, `ValidationDfp`, `Nss`, `IdMihnati1`, `DerogationAge`, `IDCommunn`, `IDWilayaa`, `IDCommunR`, `IDWilayaR`, `sansParant`, `Nin`, `NumActeNais`, `IDPreinscrit`, `Premier`, `Tel`, `niscolaire`, `annescolaire`, `datesortirscolaire`, `numcertificatscolaire`, `datecertificatscolaire`, `email`, `Tel2`, `email2`, `photo`, `ninscscolaire`, `boursier`, `create_time`, `update_time`, `data_sync_time`) VALUES (3274763, 258802, 'لعيفاوي', 'laifaoui', 'خالد', 'khaled', '1994/10/14', 'medjana', 'مجانة', '0001126VC3407', 0, 1, 20, 'sasi', 'ساسي', 'dadache', 0, 'fadila', 0, 'دداش', 1, 'فضيلة', 0, NULL, 0, 0, 26631, 16, '2026-03-25', 1, 0, 0, 'بلدية مجانة', 'comune  medjana', NULL, 1, 0, 0, NULL, 0, 0, 3413, 34, 3413, 34, 255, 109941188005520006, 00552, 0, 0, NULL, NULL, '2012/2011', '2012-06-30', 104, '2026-04-08', NULL, NULL, NULL, NULL, NULL, 0, '2026-06-02 00:00:00', '2026-06-02', NULL);

-- Table: apprenant
INSERT IGNORE INTO `apprenant` (`IDapprenant`, `IDCandidat`, `IDEmployeur`, `IDMaitre_Apprenti`, `IDSection`, `NumActe`, `DateActe`, `NumValidation`, `Datevalidation`, `DateInstalation`, `IDDecision_orie`, `Obs`, `Nccp`, `statut`, `Valide`, `Groupe`, `NomEmployeur`, `AddresseEmployeur`, `NomEmployeurFr`, `NatureEmployeur`, `NomUser`, `Motdepass`, `urlauth`, `hash`, `create_time`, `update_time`, `data_sync_time`, `Salairepere`) VALUES (5548299, 3274761, 0, 0, 203266, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, 'actif', 0, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, '2026-06-02', '2026-06-02', NULL, 0);
INSERT IGNORE INTO `apprenant` (`IDapprenant`, `IDCandidat`, `IDEmployeur`, `IDMaitre_Apprenti`, `IDSection`, `NumActe`, `DateActe`, `NumValidation`, `Datevalidation`, `DateInstalation`, `IDDecision_orie`, `Obs`, `Nccp`, `statut`, `Valide`, `Groupe`, `NomEmployeur`, `AddresseEmployeur`, `NomEmployeurFr`, `NatureEmployeur`, `NomUser`, `Motdepass`, `urlauth`, `hash`, `create_time`, `update_time`, `data_sync_time`, `Salairepere`) VALUES (5548300, 3274762, 0, 0, 203266, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, 'actif', 0, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, '2026-06-02', '2026-06-02', NULL, 0);
INSERT IGNORE INTO `apprenant` (`IDapprenant`, `IDCandidat`, `IDEmployeur`, `IDMaitre_Apprenti`, `IDSection`, `NumActe`, `DateActe`, `NumValidation`, `Datevalidation`, `DateInstalation`, `IDDecision_orie`, `Obs`, `Nccp`, `statut`, `Valide`, `Groupe`, `NomEmployeur`, `AddresseEmployeur`, `NomEmployeurFr`, `NatureEmployeur`, `NomUser`, `Motdepass`, `urlauth`, `hash`, `create_time`, `update_time`, `data_sync_time`, `Salairepere`) VALUES (5548301, 3274763, 0, 0, 203266, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, 'actif', 0, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, '2026-06-02', '2026-06-02', NULL, 0);
INSERT IGNORE INTO `apprenant` (`IDapprenant`, `IDCandidat`, `IDEmployeur`, `IDMaitre_Apprenti`, `IDSection`, `NumActe`, `DateActe`, `NumValidation`, `Datevalidation`, `DateInstalation`, `IDDecision_orie`, `Obs`, `Nccp`, `statut`, `Valide`, `Groupe`, `NomEmployeur`, `AddresseEmployeur`, `NomEmployeurFr`, `NatureEmployeur`, `NomUser`, `Motdepass`, `urlauth`, `hash`, `create_time`, `update_time`, `data_sync_time`, `Salairepere`) VALUES (5548302, 3274759, 0, 0, 203266, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, 'actif', 0, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, '2026-06-02', '2026-06-02', NULL, 0);
INSERT IGNORE INTO `apprenant` (`IDapprenant`, `IDCandidat`, `IDEmployeur`, `IDMaitre_Apprenti`, `IDSection`, `NumActe`, `DateActe`, `NumValidation`, `Datevalidation`, `DateInstalation`, `IDDecision_orie`, `Obs`, `Nccp`, `statut`, `Valide`, `Groupe`, `NomEmployeur`, `AddresseEmployeur`, `NomEmployeurFr`, `NatureEmployeur`, `NomUser`, `Motdepass`, `urlauth`, `hash`, `create_time`, `update_time`, `data_sync_time`, `Salairepere`) VALUES (5548303, 3274760, 0, 0, 203266, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, 'actif', 0, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, '2026-06-02', '2026-06-02', NULL, 0);

-- No records for apprenant_absence

-- No records for apprenant_fin

-- No records for apprenant_section_semstre

-- No records for apprenant_section_semstre_module

SET FOREIGN_KEY_CHECKS = 1;
